In [10]:
import numpy as np

In [11]:
asList = [1,2,3]
asArray = np.array([1,2,3]) # 1D array
rowVec = np.array([[1,2,3]]) # row
colVec = np.array([[1],[2],[3]]) # column

In [12]:
print(f'asList: {np.shape(asList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec: {rowVec.shape}')
print(f'colVec: {colVec.shape}')

asList: (3,)
asArray: (3,)
rowVec: (1, 3)
colVec: (3, 1)


In [13]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6,9])
vPlusW = v + w
uPlusW = u + w  # error! dimensions mismatched!

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# can you add a row vector to a column vector
v = np.array([[4,5,6]]) # row vector
w = np.array([[10,20,30]]).T # column vector
v + w

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

Here, Python is implementing an operation called broadcasting.

In [ ]:
# vector-scalar multiplication
s = 2
a = [3,4,5] # as list
b = np.array(a) # as np array
print(a*s)
print(b*s)

[3, 4, 5, 3, 4, 5]
[ 6  8 10]


In [ ]:
s = 2.0
a = [3,4,5] # as list
b = np.array(a) # as np array
print(a*s)
print(b*s)

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
# scalar-vector addition
s = 2
v = np.array([3,6])
s + v

array([5, 8])

In [ ]:
# vector broadcasting in python
v = np.array([[1,2,3]]).T # col vector
w = np.array([[10,20]]) # row vector
v + w # addition with broadcasting

array([[11, 21],
       [12, 22],
       [13, 23]])

In [ ]:
v = np.array([1,2,3,7,8,9])
v_dim = len(v) # math dimensionality
v_mag = np.linalg.norm(v) # math magnitude, length, or norm

In [ ]:
# dot product
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
np.dot(v,w)

np.int64(70)

In [ ]:
s = 10
np.dot(s*v,w)

np.int64(700)

In [ ]:
a = np.array([0,1,2])
b = np.array([3,5,8])
c = np.array([13,21,34])

# the dot product is distributive
res1 = np.dot(a,b+c)
res2 = np.dot(a,b) + np.dot(a,c)

In [ ]:
# Hadamard (element-wise) multiplication
a = np.array([5,4,8,2])
b = np.array([1,0,.5,1])
a*b

array([5., 0., 4., 2.])

Hadamard multiplication is a convenient way to organize multiple scalar multiplications. For example, imagine you have data on the number of widgets sold in different shops and the price per widget at each shop. You could represent each variable as a vector, and then Hadamard-multiply those vectors to compute the widget revenue per shop (this is different from the total revenue across all shops, which would be computed as the dot product).

**Orthogonal vector Decomposition**

To decompose a vector or matrix means to break up that matrix into multiple simpler pieces. Decompositions are used to reveal information that is hidden in a matrix, to make the matrix easier to work with, or for data compression. It is no understatement to write that much of linear algebra (in the abstract and in practice) involves matrix decompositions. Matrix decompositions are a big deal.

Project a point at the head of $\mathbf{b}$ onto a vector $\mathbf{a}$ with minimum distance, we need a formula to compute $\beta$ such that the length of the projection vector $(\mathbf{b}-\beta{\mathbf{a}})$ is minimized.

We deduce that $(\mathbf{b}-\beta{\mathbf{a}})$ is orthogonal to $\beta{\mathbf{a}}$, which means both vectors are perpendicular. And that means the dot between them is zero

$\mathbf{a^T}(\mathbf{b}-\beta{\mathbf{a}}) = 0$

Solving the orthogonal projection problem

$\mathbf{a^Tb} - \beta\mathbf{a^Ta} = 0 \\$
    $\hspace{1cm}\beta\mathbf{a^Ta} = \mathbf{a^Tb}\\$
    $\hspace{2cm}\beta = \frac{\mathbf{a^Tb}}{\mathbf{a^Ta}}$


the parallel component of $\mathbf{b}$ with respect to $\mathbf{a}$

$\mathbf{b}_{\|\mathbf{a}}=\mathbf{a}\frac{\mathbf{b^T}\mathbf{a}}{\mathbf{a^T}\mathbf{a}}$

In [ ]:
a = np.array([[1],[2]])

b = np.array([[2],[1]])

# @ is matrix multiplication operator.
beta = (a.T @ b) @ np.linalg.inv(a.T @ a)
print(beta)

[[0.8]]


decompose vector $\mathbf{t}$ into sum of two other vectors that are orthogonal and parallel to vector $\mathbf{r}$

Computing the parallel component of $\mathbf{t}$ with respect to $\mathbf{r}$

$\mathbf{t}_{\|\mathbf{r}}=\mathbf{r}\frac{\mathbf{t^T}\mathbf{r}}{\mathbf{r^T}\mathbf{r}}$

Computing the perpendicular component by subtracting the parallel component from the original vector.

$\mathbf{t}=\mathbf{t}_{\perp\mathbf{r}}+\mathbf{t}_{\|\mathbf{r}}$

$\mathbf{t}_{\perp\mathbf{r}}=\mathbf{t}-\mathbf{t}_{\|\mathbf{r}}$

To prove that the perpendicular component is orthogonal to the reference vector, we show that the dot product between them is zero:

$(\mathbf{t}_{\perp\mathbf{r}})^\mathbf{T}\mathbf{r}=0$

$(\mathbf{t}-\mathbf{r}\frac{\mathbf{t^T}\mathbf{r}}{\mathbf{r^T}\mathbf{r}})^\mathbf{T}\mathbf{r}=0$

**Summary**

- A vector is an ordered list of numbers that is placed in a column or in a row. The
number of elements in a vector is called its dimensionality, and a vector can be
represented as a line in a geometric space with the number of axes equal to the
dimensionality.

- Several arithmetic operations (addition, subtraction, and Hadamard multiplica‐
tion) on vectors work element-wise.

- The dot product is a single number that encodes the relationship between two
vectors of the same dimensionality, and is computed as element-wise multiplica‐
tion and sum.

- The dot product is zero for vectors that are orthogonal, which geometrically
means that the vectors meet at a right angle.

- Orthogonal vector decomposition involves breaking up a vector into the sum
of two other vectors that are orthogonal and parallel to a reference vector. The
formula for this decomposition can be rederived from the geometry, but you
should remember the phrase “mapping over magnitude” as the concept that that
formula expresses.

In [16]:
import numpy as np
import matplotlib.pyplot as plt

v = np.array([[1],[2]])
w = np.array([[1],[5]])


